### ISSUE TITLE
can't find conanbuildinfo.json

### ISSUE THREAD

**Issue by iniside** [adamrehn/ue4-opencv-demo#1]
Can't compile sample project.

I'm using Master branch, and conanbuildinfo.json is not in directory of OpenCVDemo module.

It is also nowhere to be found in other folders (conan, Intermediate).

Should that file be automatically generated in the same folder as uproject file, created manually or it is created in some specific folder and needs to be copied manually ?

**Comment by king1107955613** [comment]
How did you solve it? I met the same problem.

**Comment by adamrehn** [comment]
This file is generated by the command `conan install . --profile ue4`, which is run automatically by [OpenCVDemo.Build.cs](https://github.com/adamrehn/ue4-opencv-demo/blob/master/project/OpenCVDemo/Source/OpenCVDemo/OpenCVDemo.Build.cs). If you're seeing compilation errors indicating that the file is missing then you've missed one of the setup steps from the README.
