### ISSUE TITLE
Strange behavior of the imshow method (grey image after recompile)

### ISSUE THREAD

**Issue by matteogiuliano** [adamrehn/ue4-opencv-demo#4]
Hello,
thank you for this sample project, it really helped me.
I'm opening this issue because I'm experiencing a strange behavior in the imshow method integrating OpenCV using conan-ue4cli.
I modified the "OpenCVBlueprint.cpp" code like this:

```
#include "OpenCVBlueprint.h"
#include "opencv2/core.hpp"
#include <opencv2/core/version.hpp>
#include <opencv2/features2d.hpp>
#include <opencv2/imgproc.hpp>
#include "opencv2/highgui/highgui.hpp"

FString UOpenCVBlueprint::GetOpenCvVersion() {
	using namespace cv;
	Mat image = Mat::ones(360, 640, CV_8U);
	image = image * 255;
	//circle(image, Point(180, 320), 50, 75, 10);
	cv::imshow("Test image", image);
	cv::waitKey(1);
	return FString(CV_VERSION);
}
```

It compiles just fine and when launched it correctly displays a white image.
When I uncomment the "circle(image, Point(180, 320), 50, 75, 10);" line and click compile in the Unreal Editor the code successfully compiles but when I run it, it displays a completely grey image.
If then I close and reopen the editor **without recompiling the code** I correcly see a gray circle on a white background.

This same behavior seems to repeat every time I change a line of code that modifies the Mat passed as a parameter to the imshow method.

I'm on UE4.25, on Windows 10, and I tried with OpenCV 3.3 and 3.4.

Have you got any idea about why this is happening and how to solve it?

Thank you.

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been drowning in work over the past few months and progress on addressing my GitHub backlog has been frustratingly slow.

There are a few possible causes for this sort of behaviour, and unfortunately I'm not particularly qualified to diagnose any of them. The most likely suspects would be issues with two concurrent OpenGL contexts existing within the same process and clobbering one another's thread-local variables, or issues with the Windows event loop system around window repainting.

I'm not sure how OpenCV's HighGUI system handles windowing and event loops under the hood, but in general I wouldn't expect this use case to work out of the box, and I certainly wouldn't expect calling a blocking function like `cv::waitKey()` on the Unreal Engine game thread to play nicely with Unreal's own event system. A more Unreal-friendly approach might be to load the OpenCV matrix data into an Unreal texture and then display it within your application's existing viewport. I know my colleague @ImmortalEmperor has used the Unreal API for copying raw image data into and out of textures at runtime before, he might be able to direct you to the documentation for the relevant classes/functions.

**Comment by matteogiuliano** [comment]
Thank you, I already used the workaround of copying openCV's data to an Unreal texture. As of now, it's working fine.

**Comment by adamrehn** [comment]
Terrific, I'm glad you managed to get it working nicely in the end!
